version: '2'

services:
  kadira-engine:
    image: vladgolubev/kadira-engine
    ports:
      - "11011:11011"
    environment:
      - PORT=11011
      - KADIRA_MONGO_URL=mongodb://mongo:27017
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_SHARD_URL_one=mongodb://mongo:27017
      - MONGO_SHARD=one
    depends_on:
     - mongo
  kadira-rma:
    image: dkoo761/kadira-rma
    environment:
      - MONGO_SHARD=one
      - KADIRA_MONGO_URL=mongodb://mongo:27017
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
     - mongo

  kadira-ui:
    image: vladgolubev/kadira-ui
    ports:
      - "4000:4000"
    environment:
      - KADIRA_MONGO_URL=mongodb://mongo:27017
      - MONGO_SHARD=one
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_SHARD_URL_one=mongodb://mongo:27017
    depends_on:
     - mongo
  mongo:
    image: mongo:latest
    ports:
     - "27137:27017"
    volumes:
     - ./mongodb:/data/db
  mongo-express:
    image: mongo-express:latest
    depends_on:
     - mongo
    ports:
     - "8120:8081"     
